// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38rUP6uEhr10_0RA62bVLzGKKaqRuA9g',
    appId: '1:1021043862030:web:0af2f9c15dcf1738af2a5f',
    messagingSenderId: '1021043862030',
    projectId: 'hyfeel-54cd2',
    authDomain: 'hyfeel-54cd2.firebaseapp.com',
    storageBucket: 'hyfeel-54cd2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOcq7BGmgK_9590JqXCUIOO9roMrjxr9w',
    appId: '1:1021043862030:android:b11079fb82fffcddaf2a5f',
    messagingSenderId: '1021043862030',
    projectId: 'hyfeel-54cd2',
    storageBucket: 'hyfeel-54cd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9f2aT9U5PiAKxeOjaDQ0rA7OMUy9FuRg',
    appId: '1:1021043862030:ios:8f59c86954b9d770af2a5f',
    messagingSenderId: '1021043862030',
    projectId: 'hyfeel-54cd2',
    storageBucket: 'hyfeel-54cd2.firebasestorage.app',
    iosBundleId: 'com.example.tfgMonitorH2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9f2aT9U5PiAKxeOjaDQ0rA7OMUy9FuRg',
    appId: '1:1021043862030:ios:8f59c86954b9d770af2a5f',
    messagingSenderId: '1021043862030',
    projectId: 'hyfeel-54cd2',
    storageBucket: 'hyfeel-54cd2.firebasestorage.app',
    iosBundleId: 'com.example.tfgMonitorH2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD38rUP6uEhr10_0RA62bVLzGKKaqRuA9g',
    appId: '1:1021043862030:web:9c67c7c2b02d44adaf2a5f',
    messagingSenderId: '1021043862030',
    projectId: 'hyfeel-54cd2',
    authDomain: 'hyfeel-54cd2.firebaseapp.com',
    storageBucket: 'hyfeel-54cd2.firebasestorage.app',
  );
}
